{{- if not .Values.secret.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "issuehub.fullname" . }}
  labels:
    {{- include "issuehub.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITHUB_API_TOKEN: {{ .Values.secret.data.githubApiToken | quote }}
  DATABASE_URL: {{ .Values.secret.data.databaseUrl | quote }}
  NEXTAUTH_SECRET: {{ .Values.secret.data.nextAuthSecret | quote }}
  NEXTAUTH_URL: {{ .Values.secret.data.nextAuthUrl | quote }}
{{- end }}
